# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: NeverTaking Support
repo_url: https://github.com/alanpt/documentation-test
repo_name: alanpt/support
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  icon:
    logo: material/library 
  icon:
    repo: fontawesome/brands/git-alt 
    
  palette: 
    # Palette toggle for light mode
    - scheme: light green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
#    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
#    - navigation.sections
#    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    
    
edit_uri: edit/master/docs/
markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break 
  - toc:
      permalink: '#' # heading anchor 
      slugify: !!python/name:pymdownx.slugs.uslugify 
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX  
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  
  
plugins:
  - search
  - link-marker

  - mkdocs-add-teaser:
        teaser_class: 'teaser'
        add_to_meta: true
  - tags:
      tags_file: Advanced/tags.md

  - git-revision-date-localized
  - git-authors:
        show_email_address: false
        fallback_to_empty: false
        sort_authors_by: contribution 
        
  - roamlinks 
    #- autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
