name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-exclude
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip3 install mkdocs-git-authors-plugin
      - run: pip install mkdocs-link-marker
      - run: pip install mkdocs-add-teaser
      - run: pip install mkdocs-categories-plugin

      
      - run: mkdocs gh-deploy --force
